language: php
php:
- 5.6
- 7.0
install: composer update --dev
script:
- "./run_tests.sh"
notifications:
  email:
    recipients:
    - daniel4w@gmx.de
    - daniel.weise@concepts-and-training.de
    on_success: always
    on_failure: always
env:
  global:
    secure: Anq3Ysar2YWXC1Rn5+rggiXiH4IRp8BPjFyKQjdEcLRhJfUGvFvuLXkE8n0iTk1dOuOrh13PwBw7kjokT/rfVDkFAIhxBTDh+8eK3EXM3KFRI+ipBWDXzIRdNqVeRAkQ1Eh1UyuwfQ4jd3zfRboGD8jG+wMbEey3GNs+mqC0XUaoJb5OisQBK+5Y8JfL3zJ4Vs6v19Hy05ZeGXgS4wGIHs2W3Klo6uT0cDIfirvR5ikTCQT1L5otSvjo9jx3OnfvvJc+oNy0vV/W/f5tW4tvgn/ChEp7jOZzb4KzzD3+IyDXjf6PvScC0McVMRIee+2aIxpFpJx59uZd7O3pIiGIdypVsbY6eCKoakMlmTfIkWsmM7AW+JKoXJkUc6SxKbmP3lgTkigW50F4ErJXiTCwfQyQ1PqHHbxNpCXxHgjPrypl73hbOAj0modTQWoOu1Xl3xXDpZFBqfgig4brk3uQ65F+eAw/Id1OI9W5lCWoQiHqVM5CvSKns5XS0MryjZKlus3OSCR8PnN0vH2WfsDLxh/OyR6jtfPbKCkCWJ8xxZc9pmOhoBHL7Q/ovieROQ3BWcQtdXcpTgvPUaGrgHFR/UsxFVVoj7ApSoENZtSaLjJxVlu4hsCF0hUT8TgWp31NZU/8KSTAkLIIfDWTSSrHUaWZhyFXSbpXBcABOzkmxXU=
after_success: ./update-gh-pages.sh
